name: flutter_downloader
description: A plugin for creating and managing download tasks. Supports iOS and Android.
version: 1.8.2
homepage: https://github.com/fluttercommunity/flutter_downloader
maintainer: Hung Duy Ha (@hnvn)

flutter:
  plugin:
    platforms:
      android:
        package: vn.hunghd.flutterdownloader
        pluginClass: FlutterDownloaderPlugin
      ios:
        pluginClass: FlutterDownloaderPlugin

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.10.5"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.1
  flutter_test:
    sdk: flutter
